# Base image (Dockerfile-base)
FROM python:bookworm AS base

WORKDIR /app

# Update apt and install git
RUN apt-get update && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt